sudo: false
language: elixir
matrix:
  include:
    - otp_release: 22.0
      elixir: 1.8
      env:
        - CHECK_FORMAT=true
    - otp_release: 23.0
      elixir: 1.10.3
      env:
        - CHECK_FORMAT=true
env:
  global:
    - MIX_HOME=$(pwd)/.mix
cache:
  directories:
  - deps
  - _build
install:
  - mkdir -p $MIX_HOME
  - mix local.hex --force
  - mix local.rebar --force
before_script:
  - mix deps.get
  - mix compile --warnings-as-errors
  - MIX_ENV=test mix compile --warnings-as-errors
script:
  - mix docs
  - mix credo --strict
  - MIX_ENV=test mix credo --strict
  - mix test
  - mix dialyze
  - if [ "$CHECK_FORMAT" == "true" ]; then mix format --check-formatted; fi
